# Flask Pod
apiVersion: v1
kind: Pod
metadata:
  name: flask-pod
  namespace: flask-app
spec:
  containers:
  - name: flask
    image: <dockerhub-username>/flask-two-tier:latest
    ports:
      - containerPort: 5000

